"""Figure 1: pairwise scatter of four substrates, with marginal histograms
and pairwise correlations.  Also writes Table 1 (descriptives) and
Table 2 (4x4 substrate correlation matrix) as LaTeX.

Run:
    python -m analysis.paper5_horserace.fig01_substrate_covariance
"""
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

ROOT = Path("/Volumes/BIGDATA/HYDE35")
PANEL = ROOT / "analysis/data/deep_determinants_horserace.parquet"
FIG = ROOT / "analysis/figures/paper5_horserace/fig01_substrate_covariance.pdf"
TAB1 = ROOT / "analysis/figures/paper5_horserace/tab01_descriptives.tex"
TAB2 = ROOT / "analysis/figures/paper5_horserace/tab02_substrate_correlations.tex"

SUBSTRATES = [
    "sigma_v_T_pre1750",
    "H_pred_pwadj",
    "ancestral_yield_log",
    "pandemic_intensity_norm",
]
OUTCOMES = [
    "log_pop_growth_1950_2025",
    "urban_change_1950_2025",
    "log_gdppc_2015",
    "dt_timing_year",
]
CONTROLS = [
    "abs_lat",
    "log_area",
    "landlocked",
    "ruggedness_proxy",
    "log_dist_neolithic",
]

# Long labels for the pairplot axes (LaTeX-safe for matplotlib w/ usetex=False)
AXIS_LABELS = {
    "sigma_v_T_pre1750": r"$\sigma_v^T$ (1421-1750)",
    "H_pred_pwadj": r"Predicted Het ($H_i$)",
    "ancestral_yield_log": r"Anc. crop yield (log)",
    "pandemic_intensity_norm": r"Pre-1500 pandemic",
}

# Short labels for LaTeX table column headers
SHORT_LABELS = {
    "sigma_v_T_pre1750": r"$\sigma_v^T$",
    "H_pred_pwadj": r"$H_i$",
    "ancestral_yield_log": r"Crop yield",
    "pandemic_intensity_norm": r"Pandemic",
}

# Full labels for Table 1 row names
FULL_LABELS = {
    "sigma_v_T_pre1750": r"Climate vol.\ $\sigma_v^T$ (pre-1750)",
    "H_pred_pwadj": r"Predicted heterozygosity $H_i$",
    "ancestral_yield_log": r"Ancestral crop yield (log)",
    "pandemic_intensity_norm": r"Pre-1500 pandemic intensity",
    "log_pop_growth_1950_2025": r"$\Delta\log P_{1950\to2025}$",
    "urban_change_1950_2025": r"$\Delta$ urban share 1950--2025",
    "log_gdppc_2015": r"$\log$ GDPpc 2015",
    "dt_timing_year": r"DT timing year",
    "abs_lat": r"Absolute latitude",
    "log_area": r"$\log$ area",
    "landlocked": r"Landlocked",
    "ruggedness_proxy": r"Ruggedness (log)",
    "log_dist_neolithic": r"$\log$ distance from Neolithic",
}


# ---------------------------------------------------------------------------
# Table 1 — Descriptive statistics
# ---------------------------------------------------------------------------

def _descriptives_table(df: pd.DataFrame, cols: list[str], out: Path) -> None:
    """Write mean / SD / N for each column as a LaTeX tabular."""
    rows = []
    for c in cols:
        s = df[c].dropna()
        rows.append((FULL_LABELS.get(c, c), s.mean(), s.std(), len(s)))

    n_sub = len(SUBSTRATES)
    n_out = len(OUTCOMES)

    with open(out, "w") as f:
        f.write("% Table 1 — Descriptive statistics\n")
        f.write("% Generated by fig01_substrate_covariance.py\n")
        f.write("\\begin{tabular}{lrrr}\n\\toprule\n")
        f.write("Variable & Mean & SD & $N$ \\\\\n\\midrule\n")

        f.write("\\multicolumn{4}{l}{\\textit{Substrates}} \\\\\n")
        for lbl, mn, sd, n in rows[:n_sub]:
            f.write(f"\\quad {lbl} & {mn:.3f} & {sd:.3f} & {n} \\\\\n")

        f.write("\\midrule\n\\multicolumn{4}{l}{\\textit{Outcomes}} \\\\\n")
        for lbl, mn, sd, n in rows[n_sub : n_sub + n_out]:
            f.write(f"\\quad {lbl} & {mn:.3f} & {sd:.3f} & {n} \\\\\n")

        f.write("\\midrule\n\\multicolumn{4}{l}{\\textit{Geography controls}} \\\\\n")
        for lbl, mn, sd, n in rows[n_sub + n_out :]:
            f.write(f"\\quad {lbl} & {mn:.3f} & {sd:.3f} & {n} \\\\\n")

        f.write("\\bottomrule\n\\end{tabular}\n")

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Table 2 — Substrate correlation matrix
# ---------------------------------------------------------------------------

def _correlation_table(corr: pd.DataFrame, out: Path) -> None:
    """Write a 4x4 LaTeX correlation matrix; |r| > 0.4 in bold."""
    short_cols = [SHORT_LABELS.get(c, c) for c in corr.columns]
    short_rows = [SHORT_LABELS.get(c, c) for c in corr.index]

    with open(out, "w") as f:
        f.write("% Table 2 — Substrate pairwise correlations\n")
        f.write("% Generated by fig01_substrate_covariance.py\n")
        f.write("% Correlations |r| > 0.4 are in bold.\n")
        ncols = len(SUBSTRATES)
        f.write("\\begin{tabular}{l" + "r" * ncols + "}\n\\toprule\n")
        f.write(" & " + " & ".join(short_cols) + " \\\\\n\\midrule\n")
        for row_name, row_label in zip(corr.index, short_rows):
            cells = []
            for v in corr.loc[row_name]:
                if abs(v) > 0.4:
                    cells.append(f"\\textbf{{{v:.2f}}}")
                else:
                    cells.append(f"{v:.2f}")
            f.write(row_label + " & " + " & ".join(cells) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Figure 1 — Pairplot
# ---------------------------------------------------------------------------

def _pairplot(sub: pd.DataFrame, out: Path) -> None:
    """4x4 seaborn pairplot with regression lines and histograms on diagonal."""
    sns.set_theme(style="ticks", font_scale=0.9)

    renamed = sub.rename(columns=AXIS_LABELS)

    g = sns.pairplot(
        renamed,
        kind="reg",
        diag_kind="hist",
        height=2.2,
        plot_kws={
            "scatter_kws": {"alpha": 0.45, "s": 8, "color": "steelblue"},
            "line_kws": {"color": "C3", "lw": 1.5},
            "ci": 95,
        },
        diag_kws={"bins": 20, "color": "steelblue", "edgecolor": "white"},
    )

    # Tighten tick labels
    for ax in g.axes.flatten():
        if ax is not None:
            ax.tick_params(axis="both", labelsize=7)

    # Add Pearson r annotations on upper triangle
    col_names = renamed.columns.tolist()
    for i in range(len(col_names)):
        for j in range(len(col_names)):
            if j > i:  # upper triangle
                ax = g.axes[i, j]
                x = sub.iloc[:, j]
                y = sub.iloc[:, i]
                mask = x.notna() & y.notna()
                if mask.sum() > 2:
                    r = float(np.corrcoef(x[mask], y[mask])[0, 1])
                    ax.set_visible(True)
                    ax.text(
                        0.5, 0.5,
                        f"r = {r:.2f}",
                        transform=ax.transAxes,
                        ha="center", va="center",
                        fontsize=9,
                        fontweight="bold" if abs(r) > 0.4 else "normal",
                        color="C3" if abs(r) > 0.4 else "0.3",
                    )
                    ax.set_xticks([])
                    ax.set_yticks([])
                    # Remove spines for cleaner look
                    for spine in ax.spines.values():
                        spine.set_visible(False)

    g.figure.suptitle(
        "Figure 1: Substrate covariance — four pre-industrial deep determinants",
        y=1.01, fontsize=10,
    )
    g.figure.tight_layout()
    g.figure.savefig(out, bbox_inches="tight", dpi=150)
    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    df = pd.read_parquet(PANEL)
    print(f"Panel loaded: {df.shape[0]} rows x {df.shape[1]} cols")

    # Table 1: descriptives on full sample (dropna per variable)
    _descriptives_table(df, SUBSTRATES + OUTCOMES + CONTROLS, TAB1)

    # Subset to rows with all four substrates present
    sub = df[SUBSTRATES].dropna()
    print(f"Substrate subset (all 4 non-null): {len(sub)} rows")

    # Table 2: correlation matrix on substrate subset
    corr = sub.corr().round(3)
    print("\nSubstrate correlations:")
    print(corr.to_string())
    print(f"\nMax |r| off-diagonal: {corr.where(~np.eye(4, dtype=bool)).abs().max().max():.3f}")
    _correlation_table(corr, TAB2)

    # Figure 1
    FIG.parent.mkdir(parents=True, exist_ok=True)
    _pairplot(sub, FIG)

    print("\nAll outputs written.")


if __name__ == "__main__":
    main()
